#!/bin/bash

# ==============================================================================
# Gamble Limited - Automated Docker Build & Setup Script for Debian
# ==============================================================================
# This script automates the entire process of setting up and running the
# Gamble Limited application in a Docker container on a Debian-based system.
#
# What it does:
# 1. Checks for root privileges.
# 2. Installs necessary dependencies (Docker, Docker Compose, curl, jq).
# 3. Interactively prompts for essential configuration values.
# 4. Generates .env and config.json files.
# 5. Asks whether to enable the optional Nginx reverse proxy.
# 6. Builds and starts the Docker containers.
# 7. Provides a summary of the setup.
# ==============================================================================

# --- Color Codes for Output ---
C_RESET='\033[0m'
C_RED='\033[0;31m'
C_GREEN='\033[0;32m'
C_YELLOW='\033[0;33m'
C_BLUE='\033[0;34m'
C_CYAN='\033[0;36m'

# --- Helper Functions ---
function print_info {
    echo -e "${C_BLUE}INFO:${C_RESET} $1"
}

function print_success {
    echo -e "${C_GREEN}SUCCESS:${C_RESET} $1"
}

function print_warning {
    echo -e "${C_YELLOW}WARNING:${C_RESET} $1"
}

function print_error {
    echo -e "${C_RED}ERROR:${C_RESET} $1"
    exit 1
}

function check_root {
    if [ "$EUID" -ne 0 ]; then
        print_error "This script must be run as root. Please use 'sudo'."
    fi
}

function install_dependencies {
    print_info "Updating package lists..."
    if ! apt-get update -y; then
        print_error "Failed to update package lists."
    fi

    print_info "Installing prerequisites: curl, jq..."
    if ! apt-get install -y curl jq; then
        print_error "Failed to install curl or jq."
    fi

    # Check for Docker
    if ! command -v docker &> /dev/null; then
        print_info "Docker not found. Installing Docker..."
        curl -fsSL https://get.docker.com -o get-docker.sh
        if ! sh get-docker.sh; then
            print_error "Docker installation failed."
        fi
        rm get-docker.sh
    else
        print_info "Docker is already installed."
    fi

    # Check for Docker Compose
    if ! docker compose version &> /dev/null; then
        print_info "Docker Compose not found. Installing..."
        if ! apt-get install -y docker-compose-plugin; then
            print_error "Docker Compose installation failed."
        fi
    else
        print_info "Docker Compose is already installed."
    fi
}

function get_user_config {
    print_info "Starting interactive configuration..."

    # SECRET_KEY
    read -p "Enter a SECRET_KEY (leave blank to auto-generate): " SECRET_KEY
    if [ -z "$SECRET_KEY" ]; then
        SECRET_KEY=$(openssl rand -hex 32)
        print_info "Generated a random SECRET_KEY."
    fi

    # Admin Password
    while true; do
        read -p "Enter a password for the admin panel: " ADMIN_PASSWORD
        if [ -n "$ADMIN_PASSWORD" ]; then
            break
        else
            print_warning "Admin password cannot be empty."
        fi
    done

    # Server Port
    read -p "Enter the port to run the server on [8000]: " SERVER_PORT
    SERVER_PORT=${SERVER_PORT:-8000}

    # Cloudflare Tunnel Token
    read -p "Enter your Cloudflare Tunnel Token (optional): " CF_TUNNEL_TOKEN

    # Nginx Proxy
    read -p "Enable Nginx reverse proxy? (y/N): " ENABLE_NGINX
}

function generate_config_files {
    print_info "Generating configuration files..."

    # Create .env file
    echo "# Generated by build.sh on $(date)" > .env
    echo "SECRET_KEY=${SECRET_KEY}" >> .env
    echo "SERVER_PORT=${SERVER_PORT}" >> .env
    if [ -n "$CF_TUNNEL_TOKEN" ]; then
        echo "CF_TUNNEL_TOKEN=${CF_TUNNEL_TOKEN}" >> .env
    fi

    # Create config.json from scratch
    jq -n \
      --argjson port "$SERVER_PORT" \
      --arg pass "$ADMIN_PASSWORD" \
      '
      {
        "server": {
          "host": "0.0.0.0",
          "port": $port,
          "debug": false,
          "name": "Gamble Limited"
        },
        "security": {
          "admin_username": "admin",
          "admin_password_hash": $pass,
          "secret_key": "from_env",
          "admin_login_path": "/admin-portal",
          "house_login_path": "/the-house"
        },
        "economy": {
          "starting_cash": 1000.0,
          "starting_credits": 500.0,
          "base_exchange_rate": 10.0,
          "fluctuation_range": 0.05,
          "daily_bonus_amount": 100.0,
          "daily_bonus_cooldown_hours": 24,
          "daily_cash_amount": 50.0,
          "daily_cash_cooldown_hours": 24,
          "house_cut_percent": 5.0
        },
        "games": {
          "slots": { "enabled": true, "min_bet": 10, "max_bet": 1000, "payout_rate": 0.95 },
          "blackjack": { "enabled": true, "min_bet": 20, "max_bet": 2000 },
          "roulette": { "enabled": true, "min_bet": 5, "max_bet": 5000 },
          "plinko": { "enabled": false, "min_bet": 1, "max_bet": 1000 },
          "coinflip": { "enabled": true, "min_bet": 1, "max_bet": 10000 }
        },
        "gamble_friday": {
          "enabled": true,
          "start_hour": 6,
          "end_hour": 18,
          "timezone": "America/Chicago",
          "winnings_multiplier": 1.5,
          "win_rate_reduction": 0.05,
          "max_bet_multiplier": 3
        },
        "rate_limit": {
          "enabled": true,
          "game_requests": "30/minute",
          "api_requests": "60/minute"
        },
        "logging": {
          "level": "INFO",
          "log_to_file": true
        }
      }
      ' > config.json

    print_success "Successfully created .env and config.json."
}

function configure_nginx {
    if [[ "$ENABLE_NGINX" =~ ^[Yy]$ ]]; then
        print_info "Enabling Nginx reverse proxy..."

        # Create docker-compose.override.yml
        if [ -f "docker-compose.override.yml.template" ]; then
            cp "docker-compose.override.yml.template" "docker-compose.override.yml"
        else
            print_warning "docker-compose.override.yml.template not found."
        fi

        # Create nginx.conf from template
        if [ -f "nginx.conf.template" ]; then
            cp "nginx.conf.template" "nginx.conf"
            # Replace placeholder with user-defined port
            sed -i "s/__SERVER_PORT__/${SERVER_PORT}/g" nginx.conf
            print_success "Nginx has been enabled and configured for port ${SERVER_PORT}."
        else
            print_warning "nginx.conf.template not found. Cannot configure Nginx."
        fi

    else
        print_info "Skipping Nginx setup."
        # Clean up override files if they exist
        [ -f "docker-compose.override.yml" ] && rm "docker-compose.override.yml"
        [ -f "nginx.conf" ] && rm "nginx.conf"
    fi
}

function ensure_permissions {
    print_info "Ensuring correct permissions for data directory..."
    mkdir -p data
    # Set ownership to 1000:1000 (appuser in container)
    chown -R 1000:1000 data
    
    # Also ensure config.json is readable by everyone or specifically user 1000
    if [ -f "config.json" ]; then
        chmod 644 config.json
    fi
}

function run_docker_compose {
    print_info "Building and starting Docker containers..."
    if ! docker compose up --build -d; then
        print_error "Docker Compose failed to build and start."
    fi
    print_success "Docker containers are up and running."
}

function final_summary {
    echo -e "${C_CYAN}=================================================${C_RESET}"
    echo -e "${C_CYAN}          🎉 Setup Complete! 🎉             ${C_RESET}"
    echo -e "${C_CYAN}=================================================${C_RESET}"
    print_success "The Gamble Limited platform has been deployed."

    if [[ "$ENABLE_NGINX" =~ ^[Yy]$ ]]; then
        print_info "Application is accessible at: ${C_YELLOW}http://<your_server_ip>:80${C_RESET}"
    else
        print_info "Application is accessible at: ${C_YELLOW}http://<your_server_ip>:${SERVER_PORT}${C_RESET}"
    fi

    echo ""
    print_info "Next Steps:"
    echo -e " - To view container logs: ${C_GREEN}docker compose logs -f${C_RESET}"
    echo -e " - To stop the containers: ${C_GREEN}docker compose stop${C_RESET}"
    echo -e " - To stop and remove containers: ${C_GREEN}docker compose down${C_RESET}"
    echo ""
}

# --- Main Execution ---
main() {
    check_root
    install_dependencies
    get_user_config
    generate_config_files
    configure_nginx
    ensure_permissions
    run_docker_compose
    final_summary
}

main "$@"
